name=DCS-BIOS-Easy-Mode
author=Edward (WotUpFoo)
maintainer=Edward (WotUpFoo)
sentence=Simplify the use of DCS-BIOS by making the interfaces express themselves in terms of real world information a non-programmer would know as well as adding Asynchronous Stepper Motor support.
paragraph=DCS-BIOS-Easy-Mode was born of the clunky software-centric interface of DCS-BIOS where Flight Panel Gauges are expressed in terms of PWM pulse widths, not the span, min and max angle of the needle. This project also adds support for Stepper Motors used for gauges that are continuous - like Altimeters, Clocks
url=https://github.com/WotUpFoo/dcs-bios-arduino-easymode
category=Other
headers=DcsBiosEasyMode.h
includes=DcsBiosEasyMode.h
version=0.1
